# Generated by Django 5.2.1 on 2025-05-24 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('option', 'Option')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('underlying_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portfolio.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='portfolios', to='portfolio.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy Stock'), ('SELL', 'Sell Stock'), ('DIVIDEND', 'Dividend'), ('BUY_CALL', 'Buy Call Option'), ('SELL_CALL', 'Sell Call Option (Write)'), ('BUY_PUT', 'Buy Put Option'), ('SELL_PUT', 'Sell Put Option (Write)'), ('EXPIRE_CALL', 'Call Option Expired'), ('EXPIRE_PUT', 'Put Option Expired'), ('ASSIGN_CALL', 'Call Option Assigned'), ('ASSIGN_PUT', 'Put Option Assigned')], max_length=15)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.asset')),
                ('related_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='portfolio.optioncontract')),
            ],
        ),
    ]
